language: python
sudo: false
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/buildout-cache
python:
  - 2.7
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/buildout-cache/{eggs,downloads}
  - echo "[buildout]" > $TRAVIS_BUILD_DIR/default.cfg
  - echo "download-cache = $TRAVIS_BUILD_DIR/buildout-cache/downloads" >> $TRAVIS_BUILD_DIR/default.cfg
  - echo "eggs-directory = $TRAVIS_BUILD_DIR/buildout-cache/eggs" >> $TRAVIS_BUILD_DIR/default.cfg
  - virtualenv .
  - python bootstrap.py
install:
  - bin/buildout -n -t 3 -c travis.cfg
script:
  - bin/test -m senaite.databox
